### ISSUE TITLE
watir_install corrupts Rubymine access to chromedriver

### ISSUE THREAD

**Issue by abaird** [titusfortner/watir_install#3]
I ran watir_install and after this RubyMine was unable to find chromedriver for the test repos that I had not used watir_install in. It started working again after I removed the webdrivers gem, brew uninstalled and then installed chromedriver with homebrew. What was strange about this is that although Rubymine had trouble finding chromedriver, I could start chrome using Watir from irb just fine.

I talked with @titusfortner about why this happens and he said (in Slack):
```
Webdrivers gem v2 creates a chromedriver shim that executes a command to download/use chromedriver binary in ~/.webdrivers directory
V3 now just downloads them and overrides local execution usage
One messes with path and affects all projects
The other only affects projects that require the gem
```

To fix this we will need to:
1) upgrade to webdrivers 3 in the gemset file
2) change the created project to `require 'webdrivers'` rather than just including it in the gemfile

**Comment by titusfortner** [comment]
Fixed! Thanks.
